### ISSUE TITLE
Discord Link Not Working

### ISSUE THREAD

**Issue by decentai15** [louisbrulenaudet/hf-for-legal#3]

**Comment by louisbrulenaudet** [comment]
There was a problem with the invitation link in the [@discord](https://x.com/discord) server, the problem is now solved and here is the new entry point 🤗

If you or your friends are interested in LLM dedicated to Legal applications, don't hesitate to join the adventure - the community needs you!

[https://discord.gg/adwsfUUhw8](https://t.co/DA7z2rMVsQ)
